# Configuration Kiosk Turingine
# Structure: TYPE | COULEUR HEX | LABEL | COMMANDE
# TYPE peut être NATIVE (coupe l'accès écran virtuel) ou STD (lance en superposition)

NATIVE  | 0x440000 | Math Turingine (Natif)    | sleep 5
NATIVE  | 0x002244 | Terminal Turingine (low)  | ./.out/bin/terminal
STD     | 0x004400 | Navigateur (Firefox)      | firefox
STD     | 0x004444 | Vscode                    | code --no-sandbox --user-data-dir=/root/.config/Code
STD     | 0x200020 | btop                      | konsole -e btop
STD     | 0x111111 | Konsole                   | konsole
STD     | 0x111111 | Fichiers                  | dolphin